# Generated by Django 3.2.9 on 2021-11-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.BooleanField(default=1),
        ),
    ]
