# Generated by Django 3.2.9 on 2021-12-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211208_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(default='http://res.cloudinary.com/danangbkdn/image/upload/v1639246924/polyglot-world/avatars/default/default-avatar_n5b5k4.png', max_length=200),
        ),
    ]
