# Generated by Django 3.2.9 on 2021-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(default='avatars/default/default-avatar_n5b5k4.png', max_length=200),
        ),
    ]
