# Generated by Django 3.2.9 on 2022-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explain',
            field=models.TextField(default=''),
        ),
    ]
