# Generated by Django 3.2.9 on 2022-02-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220126_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnprogress',
            name='daily_exp',
        ),
        migrations.RemoveField(
            model_name='learnprogress',
            name='last_learned',
        ),
        migrations.AddField(
            model_name='learnprogress',
            name='lastest7dayexp',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
