# Generated by Django 3.2.9 on 2022-02-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220208_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnprogress',
            name='lastest7dayexp',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
