# Generated by Django 3.2.9 on 2022-02-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220222_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
